PYPACKAGE=turret.tankui
PYFILES=\
	__init__.py \
	progress.py \
	container.py \
	revision.py \
	lineedit.py \
	utils.py

SUBDIRS=\
    assets \
    browser \
    publish

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
