TURRET_PLUGINS=\
	default_actions.py \
	generic_action.py \
	generic_delegate.py \
	lumiere_namer.py \
	maya_actions.py \
	maya_audio.py \
	maya_bundle.py \
	maya_cachefile.py \
	maya_dlribarchive.py \
	maya_dlshader.py \
	maya_dltexture.py \
	maya_dltriplanar.py \
	maya_file.py \
	maya_fur.py \
	maya_imageplane.py \
	maya_lmcacheblend_actions.py \
	maya_lmcacheblend.py \
	maya_diskcache.py \
	maya_diskcache_actions.py \
	maya_reference.py \
	maya_scene.py \
	nuke_read.py \
	nuke_readgeo.py \
	nuke_script.py

##############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
