PYPACKAGE=turret.tankui.assets
PYFILES=\
	__init__.py \
	inspector.py \
	model.py \
	nodelist.py \
	paramlist.py \
	revisionlist.py \
	view.py \
	window.py

PYUIFILES=\
	assets.ui \
	revisionlist.ui

PYQRCFILES=\
	icons.qrc

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
