PYPACKAGE=turret
PYFILES=\
	__init__.py \
	tankscene.py \
	sandbox.py \
	mayatank.py \
	nuketank.py \
	delegate_fixtures.py \
    mayautils.py \
    nukeutils.py \
    plugins.py

SUBDIRS=\
    tankui \
    plugins \
    scripts

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
