PYPACKAGE=turret.tankui.browser
PYFILES=\
	__init__.py \
	dialog.py \
	container_results.py \
	file_filter.py \
	filter_view.py \
	revision_results.py \
	shotgun_filter.py \
	tank_filter_model.py \
	tank_filter.py

PYUIFILES=\
	browser.ui

PYQRCFILES=\
	icons.qrc

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
