# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created: Thu Nov 25 15:36:04 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Browser(object):
    def setupUi(self, Browser):
        Browser.setObjectName(_fromUtf8("Browser"))
        Browser.resize(800, 450)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Browser)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self._tankButton = QtGui.QToolButton(Browser)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tank.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._tankButton.setIcon(icon)
        self._tankButton.setCheckable(True)
        self._tankButton.setChecked(True)
        self._tankButton.setAutoExclusive(True)
        self._tankButton.setObjectName(_fromUtf8("_tankButton"))
        self.horizontalLayout_4.addWidget(self._tankButton)
        self._fileButton = QtGui.QToolButton(Browser)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._fileButton.setIcon(icon1)
        self._fileButton.setCheckable(True)
        self._fileButton.setAutoExclusive(True)
        self._fileButton.setObjectName(_fromUtf8("_fileButton"))
        self.horizontalLayout_4.addWidget(self._fileButton)
        self._shotgunButton = QtGui.QToolButton(Browser)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/shotgun.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._shotgunButton.setIcon(icon2)
        self._shotgunButton.setCheckable(True)
        self._shotgunButton.setAutoExclusive(True)
        self._shotgunButton.setObjectName(_fromUtf8("_shotgunButton"))
        self.horizontalLayout_4.addWidget(self._shotgunButton)
        spacerItem = QtGui.QSpacerItem(588, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self._searchBox = LineEdit(Browser)
        self._searchBox.setObjectName(_fromUtf8("_searchBox"))
        self.horizontalLayout_4.addWidget(self._searchBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.splitter = QtGui.QSplitter(Browser)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self._filterSwitcher = QtGui.QStackedWidget(self.splitter)
        self._filterSwitcher.setMinimumSize(QtCore.QSize(0, 150))
        self._filterSwitcher.setObjectName(_fromUtf8("_filterSwitcher"))
        self._tankFilterPage = QtGui.QWidget()
        self._tankFilterPage.setObjectName(_fromUtf8("_tankFilterPage"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self._tankFilterPage)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self._tankFilterView = TankFilterView(self._tankFilterPage)
        self._tankFilterView.setObjectName(_fromUtf8("_tankFilterView"))
        self.verticalLayout_21.addWidget(self._tankFilterView)
        self._filterSwitcher.addWidget(self._tankFilterPage)
        self._fileFilterPage = QtGui.QWidget()
        self._fileFilterPage.setObjectName(_fromUtf8("_fileFilterPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self._fileFilterPage)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self._fileFilterView = FileFilterView(self._fileFilterPage)
        self._fileFilterView.setObjectName(_fromUtf8("_fileFilterView"))
        self.verticalLayout_4.addWidget(self._fileFilterView)
        self._filterSwitcher.addWidget(self._fileFilterPage)
        self._shotgunFilterPage = QtGui.QWidget()
        self._shotgunFilterPage.setObjectName(_fromUtf8("_shotgunFilterPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self._shotgunFilterPage)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self._shotgunFilterView = ShotgunFilterView(self._shotgunFilterPage)
        self._shotgunFilterView.setObjectName(_fromUtf8("_shotgunFilterView"))
        self.verticalLayout_3.addWidget(self._shotgunFilterView)
        self._filterSwitcher.addWidget(self._shotgunFilterPage)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self._revisionFilter = QtGui.QWidget(self.layoutWidget)
        self._revisionFilter.setObjectName(_fromUtf8("_revisionFilter"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self._revisionFilter)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self._resultsSwitcher = QtGui.QStackedWidget(self._revisionFilter)
        self._resultsSwitcher.setObjectName(_fromUtf8("_resultsSwitcher"))
        self._revisionsPage1 = QtGui.QWidget()
        self._revisionsPage1.setObjectName(_fromUtf8("_revisionsPage1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self._revisionsPage1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self._filterLabel = QtGui.QLabel(self._revisionsPage1)
        self._filterLabel.setObjectName(_fromUtf8("_filterLabel"))
        self.horizontalLayout.addWidget(self._filterLabel)
        self._filterAll = QtGui.QRadioButton(self._revisionsPage1)
        self._filterAll.setChecked(True)
        self._filterAll.setObjectName(_fromUtf8("_filterAll"))
        self.horizontalLayout.addWidget(self._filterAll)
        self._filterLatest = QtGui.QRadioButton(self._revisionsPage1)
        self._filterLatest.setObjectName(_fromUtf8("_filterLatest"))
        self.horizontalLayout.addWidget(self._filterLatest)
        self._filterRecommended = QtGui.QRadioButton(self._revisionsPage1)
        self._filterRecommended.setObjectName(_fromUtf8("_filterRecommended"))
        self.horizontalLayout.addWidget(self._filterRecommended)
        spacerItem1 = QtGui.QSpacerItem(523, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self._tankRevisionsView = RevisionResultsView(self._revisionsPage1)
        self._tankRevisionsView.setRootIsDecorated(False)
        self._tankRevisionsView.setUniformRowHeights(True)
        self._tankRevisionsView.setSortingEnabled(True)
        self._tankRevisionsView.setObjectName(_fromUtf8("_tankRevisionsView"))
        self.verticalLayout_5.addWidget(self._tankRevisionsView)
        self._resultsSwitcher.addWidget(self._revisionsPage1)
        self._containersPage = QtGui.QWidget()
        self._containersPage.setObjectName(_fromUtf8("_containersPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self._containersPage)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self._tankContainersView = ContainerResultsView(self._containersPage)
        self._tankContainersView.setObjectName(_fromUtf8("_tankContainersView"))
        self.verticalLayout_6.addWidget(self._tankContainersView)
        self._resultsSwitcher.addWidget(self._containersPage)
        self.horizontalLayout_3.addWidget(self._resultsSwitcher)
        self.verticalLayout.addWidget(self._revisionFilter)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self._hintLabel = QtGui.QLabel(Browser)
        self._hintLabel.setText(_fromUtf8(""))
        self._hintLabel.setObjectName(_fromUtf8("_hintLabel"))
        self.horizontalLayout_2.addWidget(self._hintLabel)
        spacerItem2 = QtGui.QSpacerItem(728, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self._buttons = QtGui.QDialogButtonBox(Browser)
        self._buttons.setOrientation(QtCore.Qt.Horizontal)
        self._buttons.setObjectName(_fromUtf8("_buttons"))
        self.horizontalLayout_2.addWidget(self._buttons)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Browser)
        self._filterSwitcher.setCurrentIndex(0)
        self._resultsSwitcher.setCurrentIndex(1)
        QtCore.QObject.connect(self._buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Browser.accept)
        QtCore.QObject.connect(self._buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), Browser.reject)
        QtCore.QObject.connect(self._buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Browser.accept)
        QtCore.QMetaObject.connectSlotsByName(Browser)

    def retranslateUi(self, Browser):
        Browser.setWindowTitle(QtGui.QApplication.translate("Browser", "Browser", None, QtGui.QApplication.UnicodeUTF8))
        self._tankButton.setToolTip(QtGui.QApplication.translate("Browser", "Tank", None, QtGui.QApplication.UnicodeUTF8))
        self._tankButton.setText(QtGui.QApplication.translate("Browser", "...", None, QtGui.QApplication.UnicodeUTF8))
        self._fileButton.setToolTip(QtGui.QApplication.translate("Browser", "Filesystem", None, QtGui.QApplication.UnicodeUTF8))
        self._fileButton.setText(QtGui.QApplication.translate("Browser", "...", None, QtGui.QApplication.UnicodeUTF8))
        self._shotgunButton.setToolTip(QtGui.QApplication.translate("Browser", "Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self._shotgunButton.setText(QtGui.QApplication.translate("Browser", "...", None, QtGui.QApplication.UnicodeUTF8))
        self._searchBox.setText(QtGui.QApplication.translate("Browser", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self._filterLabel.setText(QtGui.QApplication.translate("Browser", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self._filterAll.setText(QtGui.QApplication.translate("Browser", "All", None, QtGui.QApplication.UnicodeUTF8))
        self._filterLatest.setText(QtGui.QApplication.translate("Browser", "Latest", None, QtGui.QApplication.UnicodeUTF8))
        self._filterRecommended.setText(QtGui.QApplication.translate("Browser", "Recommended", None, QtGui.QApplication.UnicodeUTF8))

from .file_filter import FileFilterView
from .tank_filter import TankFilterView
from .shotgun_filter import ShotgunFilterView
from ..lineedit import LineEdit
from .container_results import ContainerResultsView
from .revision_results import RevisionResultsView
import icons_rc
