PYPACKAGE=turret.tankui.publish
PYFILES=\
	__init__.py \
	dialog.py \

#PYUIFILES=

PYQRCFILES=\
	icons.qrc

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
