PYPACKAGE=turret.tankui.bundler
PYFILES=\
	__init__.py \
	window.py

PYUIFILES=\
	bundler.ui

###############################################################################
include $(SRC_DIR)/common/make/BuildTank.mk
